config/routes.rb
Group::Application.routes.draw do
  

  root 'medals#index'
  
  resources :medals do
  post 'search', :on => :collection
  end
  
  
	get "log_in" => "users#login", :as => "log_in" 
	get "my_account" => "users#my_account", :as => "my_account"
	get "log_out" => "users#logout", :as => "log_out"
	get "sign_up" => "users#new", :as => "sign_up"
	resources :users do
	post 'process_login', :on => :collection
	end

  
  get '/showmap' => 'medals#showmap'








end

app/models/medal.rb
class Medal < ActiveRecord::Base
end

app/models/user.rb
#ross did this
class User < ActiveRecord::Base  

  attr_accessor :password,:password_confirmation

  before_save :encrypt_password  

  validates_confirmation_of :password

  validates_presence_of :password, :on => :create

  validates_presence_of :email

  validates_uniqueness_of :email

  def encrypt_password

    if password.present?

      self.password_salt = BCrypt::Engine.generate_salt

      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)

    end  

  end 

  
def self.authenticate(email, password)  
    user = find_by_email(email)  
    if user && user.password_hash == BCrypt::Engine.hash_secret(password,
user.password_salt)  
      user  
    else  
      nil  
    end   
end
end

app/controllers/application_controller.rb
  class ApplicationController < ActionController::Base
    
  protected
    
    def login_required
      return true if User.find_by_id(session[:user_id])
      access_denied
      return false
    end
    def access_denied
           redirect_to :log_in
    end
    
  end
  #ross did this

app/controllers/medals_controller.rb
#this was a collaboration between the three of us
class MedalsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_medal, only: [:show, :edit, :update, :destroy]

  # GET /medals
  # GET /medals.json
  def index
    @medals = Medal.all
  end

  # GET /medals/1
  # GET /medals/1.json
  def show
  end

  # GET /medals/new
  def new
    @medal = Medal.new
  end

  # GET /medals/1/edit
  def edit
  end

  # POST /medals
  # POST /medals.json
  def create
    @medal = Medal.new(medal_params)

    respond_to do |format|
      if @medal.save
        format.html { redirect_to @medal, notice: 'Medal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medal }
      else
        format.html { render action: 'new' }
        format.json { render json: @medal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medals/1
  # PATCH/PUT /medals/1.json
  def update
    respond_to do |format|
      if @medal.update(medal_params)
        format.html { redirect_to @medal, notice: 'Medal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medals/1
  # DELETE /medals/1.json
  def destroy
    @medal.destroy
    respond_to do |format|
      format.html { redirect_to medals_url }
      format.json { head :no_content }
    end
  end
  
  def showmap
    @countries = Medal.pluck(:name)
    @key =  params[:key]
      if @key != nil
        if @key == '3'
         medal = :Bronze
        elsif @key == '2'
         medal = :Silver
        else medal = :Gold
        end
      else
        medal = :Gold
        @key = '1'
      end
    @medals = Medal.pluck(medal)
    
    if @key=='1'
      @thetitle="Gold"
    elsif @key=='2'
      @thetitle="Silver"
    elsif @key=='3'
      @thetitle="Bronze"
    end
    
  end
  
  def search
    
  @medals = Medal.find(:all, :conditions => ["name LIKE ?", "%#{params[:key]}%"])
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medal
      @medal = Medal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medal_params
      params.require(:medal).permit(:code, :name, :gold, :silver, :bronze, :showmap)
    end
end

app/controllers/users_controller.rb
#this was written by ross
class UsersController < ApplicationController  
   before_filter :login_required, :only => :my_account
  def new  
      @user = User.new  
  end 
   
    def create  
      @user = User.new(user_params)  
      if @user.save  
        redirect_to :log_in, :notice => "Signed up!"  
      else  
        render "new"  
      end  
    end 
  def login  
  
  end  
      
  def process_login  

    user = User.authenticate(params[:email], params[:password])  
  
   if user  
    
      session[:user_id] = user.id  
    
      redirect_to :my_account, :notice => "Logged in!"  
    
   else  
   
      
   
      render "login"  
   
    end  

  end  
	def logout
		session[:user_id] = nil
		redirect_to :log_in , :notice => "Logged out!"
	end 
  def my_account
     
      if session[:user_id] != nil
     
         @sessName = User.find(session[:user_id]).email
     
      else
      
         @sessName = "Guest"
      
      end
  
  end
 private
 def user_params
 params.require(:user).permit(:email, :password_hash, :password_salt, :password, :password_confirmation)
 end
 end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_field_error(model, field)
    s=""

    if !model.errors[field].empty?
      s =
        <<-EOHTML
           <div id="error_message">
             #{model.errors[field][0]}
           </div>
        EOHTML
    end

    s.html_safe
  end
end

app/helpers/medals_helper.rb
module MedalsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!--all helped with this-->
<!DOCTYPE html>
<html>
<head>
<a href="/log_in" rel="login">Log in</a>
<a href="/sign_up" rel="signup">Sign up</a>

  <title>olympic Medals 2012</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>


app/views/medals/_form.html.erb
<!--sandra did this-->
<%= form_for(@medal) do |f| %>
  <% if @medal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medal.errors.count, "error") %> prohibited this medal from being saved:</h2>

      <ul>
      <% @medal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gold %><br>
    <%= f.number_field :gold %>
  </div>
  <div class="field">
    <%= f.label :silver %><br>
    <%= f.number_field :silver %>
  </div>
  <div class="field">
    <%= f.label :bronze %><br>
    <%= f.number_field :bronze %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/medals/edit.html.erb
<h1>Editing medal</h1>

<%= render 'form' %>

<%= link_to 'Show', @medal %> |
<%= link_to 'Back', medals_path %>

app/views/medals/index.html.erb
<!--jamie did most of this-->
<html>
<head>
</head>

<body>
  
                          <h1>London Olympics 2012 Medals</h1>
  <div class='intro'>
  <p>This web application was developed by Ross Gordon, Jamie Pryde and Sandra Rubio for CS2512 AWAD.</p>
  </div>
  <div class='wholepage'>

 

  
  
  </br></br>

  <div class='twitter'>
  <a class="twitter-timeline" href="https://twitter.com/Olympics" data-widget-id="445966379225579520">Tweets by @Olympics</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>

  </br></br>
  
  <div class='livedata'>
  <p><%=button_to 'Click here', showmap_path, :class => "button", :method => :get%>to view a map of the countries that took part in the 2012 London Olympic Games and the number of gold medals they won.</p>
  </div>
  



  </br></br></br>
  
  <div class='search'>
  <h3>Search for a country</h3>
  <form action ="medals/search" method="post">
  <input name = "key" type="input" />
  <input value="Send" type="submit"/>
  </form>
  </div>
  
  </br>
  
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th style="color:goldenrod">Gold</th>
        <th style="color:silver">Silver</th>
        <th style="color:saddlebrown">Bronze</th>
      </tr>
   </thead>

    <tbody>
     <% @medals.each do |medal| %>
        <tr>
          <td><%= medal.name %></td>
          <td style="color:goldenrod"><%= medal.gold %></td>
          <td style="color:silver"><%= medal.silver %></td>
          <td style="color:saddlebrown"><%= medal.bronze %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>
  
</body>
</html>

app/views/medals/new.html.erb
<h1>New medal</h1>

<%= render 'form' %>

<%= link_to 'Back', medals_path %>

app/views/medals/search.html.erb
<!--jamie did this-->
<html>

<head>
<p><%=link_to 'Return Home', root_path%></p>
  <title>Search results</title>
</head>

<body>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th style="color:goldenrod">Gold</th>
        <th style="color:silver">Silver</th>
        <th style="color:saddlebrown">Bronze</th>
      </tr>
   </thead>

    <tbody>
     <% @medals.each do |medal| %>
        <tr>
          <td><%= medal.name %></td>
          <td style="color:goldenrod"><%= medal.gold %></td>
          <td style="color:silver"><%= medal.silver %></td>
          <td style="color:saddlebrown"><%= medal.bronze %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p><%=link_to 'Return Home', root_path%></p>
</body>

</html>

app/views/medals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @medal.name %>
</p>

<p>
  <strong>Gold:</strong>
  <%= @medal.gold %>
</p>

<p>
  <strong>Silver:</strong>
  <%= @medal.silver %>
</p>

<p>
  <strong>Bronze:</strong>
  <%= @medal.bronze %>
</p>

<%= link_to 'Edit', edit_medal_path(@medal) %> |
<%= link_to 'Back', medals_path %>

app/views/medals/showmap.html.erb
<html>
<head>
<!--sandra did this file-->
  <script type='text/javascript' src='https://www.google.com/jsapi'></script>
  <script type='text/javascript'>
   google.load('visualization', '1', {'packages': ['geomap']});
   google.setOnLoadCallback(drawMap);
  
      function drawMap() {
      var data = new google.visualization.DataTable();
      var i = 0;
      var country = new Array();
      var medals = new Array();
      var length = <%=@countries.size%>;
      var test = new Array();
      country = <%=raw @countries.as_json%>;
      medals = <%=raw @medals.as_json%>;
     
     
      data.addColumn('string', 'Country')
      data.addColumn('string', '<%=@medal%>')
      i = 0;
      while (i < length ) {
        data.addRows([[country[i], medals[i].toString()], ]);
        ++i;
      }

      var options = {};
      var colors = new Array();
      options['dataMode'] = 'regions';
      if (<%=@key%> == '2') colors = [0xDCDCDC, 0xC0C0C0 , 0x808080, 0x2F4F4F];
      else if (<%=@key%> == '1') colors = [0xFFFFC2, 0xFFD801, 0xFFCC33, 0xFFCC00];
      else colors = [0xFCD59C, 0xEE9A49, 0xCC7F32, 0x8B4500];
      options['colors'] = colors; // - to +
      options['width'] = '1024px';
      options['height'] = '648px';

      var container = document.getElementById('map_canvas');
      var geomap = new google.visualization.GeoMap(container);
      geomap.draw(data, options);
  };
  </script>
</head>

<body>
  <h1><%=@thetitle%> Medals</h1>
  </br></br>
  <div id='map_canvas'></div>
  <div class='mapcontrols'>
  <div class='mb1'><form action="/showmap" >  <input type="hidden", name="key" value='1' > <input style="font-weight: bold; padding: 5px 10px"; type ="submit" value="Check for Gold Medals"  /></form> </div>
  <div class='mb2'><form action="/showmap" > <input type="hidden", name="key" value='2' ><input style="font-weight: bold; padding: 5px 10px"; type ="submit" value="Check for Silver Medals"  /></form> </div>
  <div class='mb3'><form action="/showmap" > <input type="hidden", name="key" value='3' ><input style="font-weight: bold; padding: 5px 10px"; type ="submit" value="Check for Bronze Medals"  /></form> </div>
  

  </div>
    
</br></br>
<div class='home'>
<p><%=link_to 'Return Home', root_path%></p>
</div>
</body>

</html>

app/views/users/login.html.erb
<!--ross-->
<h1>Log in</h1>
<%= form_tag :action => 'process_login' %>
<p> 
<%= label_tag :email %><br /> 
<%= text_field_tag :email, params[:email] %> 
</p> 
<p> 
<%= label_tag :password %><br /> 
<%= password_field_tag :password %> 
</p>

<%= submit_tag "log in"%>
<p><%=link_to 'Return Home', root_path%></p>

app/views/users/my_account.html.erb
<!--ross-->
<h1>Account Info</h1>

<p>Your username is <%= @sessName %>

<br>
<a href="log_out">Log out</a>
<p><%=link_to 'Return Home', root_path%></p>

app/views/users/new.html.erb
<!--ross-->
<p><%=link_to 'Return Home', root_path%></p>
<h1>Sign Up</h1>  

  <%= form_for @user do |f| %>  

  <% if @user.errors.any? %>  

    <div class="error_messages">  

      <h2>Form is invalid</h2>  

      <ul>  

        <% for message in @user.errors.full_messages %>  

          <li><%= message %></li>  

        <% end %>  

      </ul>  

    </div>  

  <% end %>  

  <p>
  
  <%= f.label :username %><br />
  
  <%= f.text_field :email %>
  
  </p>
  
  <p>  

    <%= f.label :email %><br />  

    <%= f.text_field :email %>  

  </p>  

  <p>  

    <%= f.label :password %><br />  

    <%= f.password_field :password %>  

  </p>  

  <p>  

    <%= f.label :password_confirmation %><br />  

    <%= f.password_field :password_confirmation %>  

  </p>  

  <p class="button"><%= f.submit %></p>  

<% end %>  